# Generated by Django 4.2.16 on 2024-09-05 07:46

import apps.tasks.choices.priorities
import apps.tasks.choices.statuses
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tasks', '0002_task'),
    ]

    operations = [
        migrations.AlterField(
            model_name='task',
            name='priority',
            field=models.SmallIntegerField(choices=[apps.tasks.choices.priorities.Priority['VERY_LOW'], apps.tasks.choices.priorities.Priority['LOW'], apps.tasks.choices.priorities.Priority['MEDIUM'], apps.tasks.choices.priorities.Priority['HIGH'], apps.tasks.choices.priorities.Priority['CRITICAL']], default=3),
        ),
        migrations.AlterField(
            model_name='task',
            name='status',
            field=models.CharField(choices=[('NEW', 'NEW'), ('IN_PROGRESS', 'IN_PROGRESS'), ('PENDING', 'PENDING'), ('BLOCKED', 'BLOCKED'), ('TESTING', 'TESTING'), ('CLOSED', 'CLOSED')], default=apps.tasks.choices.statuses.Statuses['NEW'], max_length=15),
        ),
    ]
